-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agendamentos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  paciente_id uuid NOT NULL,
  profissional_id uuid NOT NULL,
  sala_id uuid,
  data_agendamento date NOT NULL,
  horario_inicio time without time zone NOT NULL,
  horario_fim time without time zone NOT NULL,
  tipo_atendimento character varying,
  status USER-DEFINED DEFAULT 'agendada'::appointment_status,
  observacoes text,
  confirmacao_via_sms boolean DEFAULT false,
  confirmacao_data timestamp with time zone,
  confirmado_por uuid,
  cancelado_em timestamp with time zone,
  cancelado_por uuid,
  motivo_cancelamento character varying,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  criado_por uuid,
  CONSTRAINT agendamentos_pkey PRIMARY KEY (id),
  CONSTRAINT agendamentos_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT agendamentos_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT agendamentos_profissional_id_fkey FOREIGN KEY (profissional_id) REFERENCES public.usuarios(id),
  CONSTRAINT agendamentos_sala_id_fkey FOREIGN KEY (sala_id) REFERENCES public.salas(id),
  CONSTRAINT agendamentos_confirmado_por_fkey FOREIGN KEY (confirmado_por) REFERENCES public.usuarios(id),
  CONSTRAINT agendamentos_cancelado_por_fkey FOREIGN KEY (cancelado_por) REFERENCES public.usuarios(id),
  CONSTRAINT agendamentos_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.anexos_prontuarios (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  evolucao_id uuid,
  prontuario_id uuid,
  nome_arquivo character varying NOT NULL,
  tipo_arquivo character varying,
  caminho_arquivo text NOT NULL,
  tamanho_bytes integer,
  descricao character varying,
  data_criacao timestamp with time zone DEFAULT now(),
  criado_por uuid NOT NULL,
  CONSTRAINT anexos_prontuarios_pkey PRIMARY KEY (id),
  CONSTRAINT anexos_prontuarios_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id),
  CONSTRAINT anexos_prontuarios_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT anexos_prontuarios_evolucao_id_fkey FOREIGN KEY (evolucao_id) REFERENCES public.evolucoes(id),
  CONSTRAINT anexos_prontuarios_prontuario_id_fkey FOREIGN KEY (prontuario_id) REFERENCES public.prontuarios(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  usuario_id uuid,
  tabela_afetada character varying NOT NULL,
  registro_id uuid,
  acao character varying,
  dados_anteriores jsonb,
  dados_novos jsonb,
  alteracoes_resumo jsonb,
  endereco_ip character varying,
  user_agent text,
  data_acao timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT audit_logs_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.clinicas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nome_clinica character varying NOT NULL CHECK (length(nome_clinica::text) > 0),
  cnpj character varying UNIQUE,
  email character varying NOT NULL CHECK (email::text ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'::text),
  telefone character varying,
  endereco text,
  cidade character varying,
  estado character varying,
  cep character varying,
  logo_url text,
  cores_primaria character varying DEFAULT '#2D6A4F'::character varying,
  cores_secundaria character varying DEFAULT '#F8F9FA'::character varying,
  cores_neutra character varying DEFAULT '#E9ECEF'::character varying,
  ativo boolean DEFAULT true,
  plano_assinatura character varying DEFAULT 'starter'::character varying,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  CONSTRAINT clinicas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dashboard_cache (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  data_cache_em timestamp with time zone DEFAULT now(),
  total_pacientes integer,
  total_agendamentos_mes integer,
  total_faturamento_mes numeric,
  taxa_confirmacao numeric,
  agendamentos_dia integer,
  pendencias_abertas integer,
  CONSTRAINT dashboard_cache_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_cache_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id)
);
CREATE TABLE public.evolucoes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  prontuario_id uuid NOT NULL,
  agendamento_id uuid,
  conteudo text NOT NULL CHECK (length(conteudo) > 0),
  observacoes_confidenciais text,
  titulo_resumo character varying,
  imutavel boolean DEFAULT false,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  criado_por uuid NOT NULL,
  CONSTRAINT evolucoes_pkey PRIMARY KEY (id),
  CONSTRAINT evolucoes_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT evolucoes_prontuario_id_fkey FOREIGN KEY (prontuario_id) REFERENCES public.prontuarios(id),
  CONSTRAINT evolucoes_agendamento_id_fkey FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos(id),
  CONSTRAINT evolucoes_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.frequencia_atendimentos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  paciente_id uuid NOT NULL,
  profissional_id uuid NOT NULL,
  agendamento_id uuid UNIQUE,
  data_atendimento date NOT NULL,
  compareceu boolean NOT NULL,
  observacoes text,
  registrado_por uuid NOT NULL,
  data_criacao timestamp with time zone DEFAULT now(),
  CONSTRAINT frequencia_atendimentos_pkey PRIMARY KEY (id),
  CONSTRAINT frequencia_atendimentos_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT frequencia_atendimentos_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT frequencia_atendimentos_profissional_id_fkey FOREIGN KEY (profissional_id) REFERENCES public.usuarios(id),
  CONSTRAINT frequencia_atendimentos_agendamento_id_fkey FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos(id),
  CONSTRAINT frequencia_atendimentos_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.lancamentos_financeiros (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  agendamento_id uuid,
  paciente_id uuid,
  descricao character varying NOT NULL,
  valor numeric NOT NULL CHECK (valor > 0::numeric),
  tipo_valor character varying DEFAULT 'credito'::character varying,
  status USER-DEFINED DEFAULT 'pendente'::payment_status,
  data_vencimento date,
  data_pagamento timestamp with time zone,
  metodo_pagamento character varying,
  observacoes text,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  criado_por uuid,
  CONSTRAINT lancamentos_financeiros_pkey PRIMARY KEY (id),
  CONSTRAINT lancamentos_financeiros_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT lancamentos_financeiros_agendamento_id_fkey FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos(id),
  CONSTRAINT lancamentos_financeiros_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT lancamentos_financeiros_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.mensalidades_pacientes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  paciente_id uuid NOT NULL,
  valor_mensalidade numeric NOT NULL CHECK (valor_mensalidade > 0::numeric),
  dia_vencimento integer NOT NULL CHECK (dia_vencimento >= 1 AND dia_vencimento <= 31),
  ativo boolean DEFAULT true,
  observacoes text,
  criado_por uuid NOT NULL,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  CONSTRAINT mensalidades_pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT mensalidades_pacientes_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT mensalidades_pacientes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT mensalidades_pacientes_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.notificacoes_fila (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  usuario_id uuid,
  tipo_notificacao character varying,
  titulo character varying,
  mensagem text,
  dados_json jsonb,
  enviado boolean DEFAULT false,
  data_criacao timestamp with time zone DEFAULT now(),
  data_envio timestamp with time zone,
  CONSTRAINT notificacoes_fila_pkey PRIMARY KEY (id),
  CONSTRAINT notificacoes_fila_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT notificacoes_fila_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.pacientes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  nome_completo character varying NOT NULL CHECK (length(nome_completo::text) > 0),
  cpf character varying UNIQUE,
  data_nascimento date,
  genero USER-DEFINED,
  email character varying,
  telefone_principal character varying,
  telefone_secundario character varying,
  endereco text,
  numero character varying,
  complemento character varying,
  cidade character varying,
  estado character varying,
  cep character varying,
  responsavel_nome character varying,
  responsavel_telefone character varying,
  responsavel_email character varying,
  responsavel_relacao character varying,
  ativo boolean DEFAULT true,
  observacoes text,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  criado_por uuid,
  CONSTRAINT pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT pacientes_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT pacientes_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.pacientes_profissionais (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  paciente_id uuid NOT NULL,
  profissional_id uuid NOT NULL,
  clinica_id uuid NOT NULL,
  data_vinculo timestamp with time zone DEFAULT now(),
  ativo boolean DEFAULT true,
  observacoes text,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT pacientes_profissionais_pkey PRIMARY KEY (id),
  CONSTRAINT pacientes_profissionais_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT pacientes_profissionais_profissional_id_fkey FOREIGN KEY (profissional_id) REFERENCES public.usuarios(id),
  CONSTRAINT pacientes_profissionais_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id)
);
CREATE TABLE public.pacote_itens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  pacote_id uuid NOT NULL,
  tipo_profissional_id uuid NOT NULL,
  profissional_id uuid,
  quantidade_sessoes integer NOT NULL DEFAULT 1 CHECK (quantidade_sessoes >= 1),
  valor_sessao numeric NOT NULL CHECK (valor_sessao > 0::numeric),
  subtotal numeric NOT NULL DEFAULT (valor_sessao * (quantidade_sessoes)::numeric),
  CONSTRAINT pacote_itens_pkey PRIMARY KEY (id),
  CONSTRAINT pacote_itens_pacote_id_fkey FOREIGN KEY (pacote_id) REFERENCES public.pacotes(id),
  CONSTRAINT pacote_itens_tipo_profissional_id_fkey FOREIGN KEY (tipo_profissional_id) REFERENCES public.tipos_profissional(id),
  CONSTRAINT pacote_itens_profissional_id_fkey FOREIGN KEY (profissional_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.pacotes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  paciente_id uuid NOT NULL,
  valor_total numeric NOT NULL DEFAULT 0 CHECK (valor_total >= 0::numeric),
  status USER-DEFINED NOT NULL DEFAULT 'pendente'::payment_status,
  metodo_pagamento character varying,
  valor_pago numeric,
  data_pagamento timestamp with time zone,
  registrado_por uuid,
  ativo boolean NOT NULL DEFAULT true,
  observacoes text,
  criado_por uuid NOT NULL,
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  atualizado_em timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pacotes_pkey PRIMARY KEY (id),
  CONSTRAINT pacotes_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT pacotes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT pacotes_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES public.usuarios(id),
  CONSTRAINT pacotes_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.pagamentos_mensalidades (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  mensalidade_id uuid NOT NULL,
  paciente_id uuid NOT NULL,
  mes_referencia date NOT NULL,
  status USER-DEFINED DEFAULT 'pendente'::payment_status,
  data_vencimento date NOT NULL,
  data_pagamento timestamp with time zone,
  valor_pago numeric CHECK (valor_pago IS NULL OR valor_pago > 0::numeric),
  metodo_pagamento character varying,
  observacoes text,
  registrado_por uuid,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  dia_vencimento bigint,
  CONSTRAINT pagamentos_mensalidades_pkey PRIMARY KEY (id),
  CONSTRAINT pagamentos_mensalidades_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT pagamentos_mensalidades_mensalidade_id_fkey FOREIGN KEY (mensalidade_id) REFERENCES public.mensalidades_pacientes(id),
  CONSTRAINT pagamentos_mensalidades_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT pagamentos_mensalidades_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.prontuarios (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  paciente_id uuid NOT NULL,
  agendamento_id uuid,
  titulo character varying NOT NULL CHECK (length(titulo::text) > 0),
  descricao text,
  diagnostico_preliminar text,
  historico_clinico text,
  alergias text,
  medicacoes text,
  visivel_para_paciente boolean DEFAULT false,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  criado_por uuid NOT NULL,
  profissional_id uuid,
  queixas text,
  CONSTRAINT prontuarios_pkey PRIMARY KEY (id),
  CONSTRAINT prontuarios_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT prontuarios_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT prontuarios_agendamento_id_fkey FOREIGN KEY (agendamento_id) REFERENCES public.agendamentos(id),
  CONSTRAINT prontuarios_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id),
  CONSTRAINT prontuarios_profissional_id_fkey FOREIGN KEY (profissional_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.relatorios (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  paciente_id uuid NOT NULL,
  profissional_id uuid NOT NULL,
  titulo character varying NOT NULL CHECK (length(titulo::text) > 0),
  pdf_url text,
  assinatura_digital text,
  observacoes text,
  criado_por uuid NOT NULL,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  arquivo_url text,
  arquivo_path text,
  tipo_arquivo character varying,
  nome_arquivo_original character varying,
  data_upload timestamp with time zone DEFAULT now(),
  CONSTRAINT relatorios_pkey PRIMARY KEY (id),
  CONSTRAINT relatorios_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT relatorios_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT relatorios_profissional_id_fkey FOREIGN KEY (profissional_id) REFERENCES public.usuarios(id),
  CONSTRAINT relatorios_criado_por_fkey FOREIGN KEY (criado_por) REFERENCES public.usuarios(id)
);
CREATE TABLE public.salas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  nome character varying NOT NULL CHECK (length(nome::text) > 0),
  descricao text,
  capacidade integer DEFAULT 1,
  equipamentos ARRAY,
  ativo boolean DEFAULT true,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  CONSTRAINT salas_pkey PRIMARY KEY (id),
  CONSTRAINT salas_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id)
);
CREATE TABLE public.servicos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  nome character varying NOT NULL,
  descricao text,
  preco_padrao numeric NOT NULL CHECK (preco_padrao >= 0::numeric),
  tempo_estimado_minutos integer,
  ativo boolean DEFAULT true,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  CONSTRAINT servicos_pkey PRIMARY KEY (id),
  CONSTRAINT servicos_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id)
);
CREATE TABLE public.tipos_atendimento (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  nome character varying NOT NULL CHECK (length(TRIM(BOTH FROM nome)) > 0),
  ativo boolean DEFAULT true,
  ordem integer DEFAULT 0,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT tipos_atendimento_pkey PRIMARY KEY (id),
  CONSTRAINT tipos_atendimento_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id)
);
CREATE TABLE public.tipos_profissional (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  clinica_id uuid NOT NULL,
  nome character varying NOT NULL CHECK (length(TRIM(BOTH FROM nome)) > 0),
  profissional_id uuid,
  valor_sessao numeric NOT NULL CHECK (valor_sessao > 0::numeric),
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  atualizado_em timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tipos_profissional_pkey PRIMARY KEY (id),
  CONSTRAINT tipos_profissional_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id),
  CONSTRAINT tipos_profissional_profissional_id_fkey FOREIGN KEY (profissional_id) REFERENCES public.usuarios(id)
);
CREATE TABLE public.usuarios (
  id uuid NOT NULL,
  clinica_id uuid NOT NULL,
  nome_completo character varying NOT NULL CHECK (length(nome_completo::text) > 0),
  cpf character varying UNIQUE,
  email character varying NOT NULL,
  telefone character varying,
  foto_perfil_url text,
  role USER-DEFINED NOT NULL DEFAULT 'recepcao'::user_role,
  especialidade character varying,
  numero_registro character varying,
  ativo boolean DEFAULT true,
  primeiro_acesso boolean DEFAULT true,
  data_criacao timestamp with time zone DEFAULT now(),
  data_atualizacao timestamp with time zone DEFAULT now(),
  deletado_em timestamp with time zone,
  reset_code character varying UNIQUE,
  reset_code_expires timestamp with time zone,
  reset_code_attempts integer DEFAULT 0,
  ultimo_reset_code_gerado timestamp with time zone,
  CONSTRAINT usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT usuarios_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT usuarios_clinica_id_fkey FOREIGN KEY (clinica_id) REFERENCES public.clinicas(id)
);